#!/usr/bin/env bash

ensure_raylib() {
	local raylib_dir="$1"
	local raylib_link="$2"
	local raylib_tarball="$raylib_dir.tar.gz"
	if [[ -d "$raylib_dir" ]]; then
		echo "raylib directory found, no problem there"
	else
		echo "raylib directory $raylib_dir not found, fetching from"
		echo "$raylib_link"
		curl -LO "$raylib_link"
		tar -xf "$raylib_tarball"
		rm "$raylib_tarball"

		echo 'removing dynamic libraries from raylib dir'
		echo 'to avoid beghe'

		mkdir -p "$raylib_dir/tmp"
		mv "$raylib_dir"/lib/*.a "$raylib_dir/tmp"
		rm -rf "$raylib_dir/lib/"
		mv "$raylib_dir/tmp/" "$raylib_dir/lib/"
	fi
}

main() {
    echo 'removing old raylib directories'
    for dir in './raylib-5.5_linux_amd64' './raylib-5.5_macos'; do
	    if [[ -d "$dir" ]]; then
            echo "removing $dir"
            rm -rf "$dir"
        fi
    done

    echo 're-downloading them'
	ensure_raylib './raylib-5.5_linux_amd64'\
                  'https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz'
	ensure_raylib './raylib-5.5_macos'\
                  'https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_macos.tar.gz'
}

main
